[package]
name = "zetamac-rs"
version = "0.1.0"
edition = "2024"
description = "Zetamac timed arithemtic test and pratice"
license = "MIT"
repository = "https://github.com/divkov575/zetamac-rs"  # Optional but recommended

[dependencies]
crossterm = "0.29"
ratatui = "0.29"
rand = "0.9"
